<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56" started-at="2019-01-24T12:31:01Z" finished-at="2019-01-24T12:31:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56" started-at="2019-01-24T12:31:01Z" finished-at="2019-01-24T12:31:01Z">
      <class name="TestNGTestCases.ValidateRegisterPageTest">
        <test-method status="FAIL" signature="validateregistrationofuser()[pri:0, instance:TestNGTestCases.ValidateRegisterPageTest@402a079c]" name="validateregistrationofuser" duration-ms="0" started-at="2019-01-24T12:31:01Z" data-provider="getdata" finished-at="2019-01-24T12:31:01Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void TestNGTestCases.ValidateRegisterPageTest.validateregistrationofuser() throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : getdata]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void TestNGTestCases.ValidateRegisterPageTest.validateregistrationofuser() throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : getdata
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateregistrationofuser -->
      </class> <!-- TestNGTestCases.ValidateRegisterPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
